pip install requests
pip install six
pip install urllib3
pip install psutil
pip install pillow
pip install opencv-python
pip install numpy
pip install sounddevice
pip install ffmpeg-python
pip install pycaw
pip install comtypes
pip install simpleaudio
pip install pydub
pip install pywin32
pip install win32gui
pip install Wave
pip install wave
pip install winregistry
pip install mss
start question.pyw
