cd C:\data
start calc.exe
start regedit
start SD.pyw
start SD2.pyw
start SD3.pyw
start FakeVirusHelper.bat
start cmdmatrix.bat
timeout 3
start FakeVirusHelper.bat
start cmdmatrix.bat
timeout 3
start FakeVirusHelper.bat
start cmdmatrix.bat
timeout 3
start FakeVirusHelper.bat
start cmdmatrix.bat
timeout 3
start FakeVirusHelper.bat
start cmdmatrix.bat
start Helper3.bat
exit